method: 'xfer'
arch: 'resnet50'
noise_sd: 0.25
exp_id: ''
METHOD:
  t_archs: 'resnet18'
  t_loadpaths: '/path/to/teacher/checkpoint.pth.tar'
  alpha: 1.0
TRAIN:
  epochs: 90
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  lr_scheduler: 'multistep'
  resume: False
  resume_ckpt: ''
DATA:
  dataset: 'imagenet'
  num_classes: 1000
  batch_size: 400
  test_batch_size: 400
  workers: 12
CERTIFY:
  load_path: ''
  start_img: 0
  skip: 100
  beta: 1.0
  certify_interval: 1
  certify_after: 200
